// Códigos de permissão do sistema
// Cada ação sensível tem um código único. Perfis são coleções de permissões.
export const PERMISSOES = {
  EXCLUIR_AGENDAMENTO: 'PERM-001',
  EDITAR_AGENDAMENTO_OUTRO_PROFISSIONAL: 'PERM-002',
  VER_RELATORIOS_FINANCEIROS: 'PERM-003',
  FECHAR_CAIXA: 'PERM-004',
  GERENCIAR_PROFISSIONAIS: 'PERM-005',
  CONFIGURAR_SERVICOS: 'PERM-006',
  VER_HISTORICO_CLIENTE: 'PERM-007',
  CANCELAR_AGENDAMENTO_CURTO_PRAZO: 'PERM-008',
  APLICAR_DESCONTO_ALTO: 'PERM-009',
  GERENCIAR_ESTOQUE: 'PERM-010',
  IMPERSONAR_USUARIO: 'PERM-011',
  ALTERAR_PLANO_ASSINATURA: 'PERM-012',
} as const

export type CodigoPermissao = typeof PERMISSOES[keyof typeof PERMISSOES]
